# Generated by Django 3.1.5 on 2021-02-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210203_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.userprofile'),
        ),
    ]
